var m_list = [{
        list: [{
            id: 1,
            url: 'http://source.aigegou.com/img/dls1.doc',
            img: 'img/data/type1.jpg',
            titles: '公司注册流程',
            looknum: '',
            downnum: '',
            type: 'word',
            cubage: '222KB',
            time: ''
        }, {
            id: 2,
            url: 'http://source.aigegou.com/img/dls2.doc',
            img: 'img/data/type1.jpg',
            titles: '办公地点和选址参考建议',
            looknum: '',
            downnum: '',
            type: 'word',
            cubage: '207KB',
            time: ''
        }, {
            id: 3,
            url: 'http://source.aigegou.com/img/dls3.doc',
            img: 'img/data/type1.jpg',
            titles: '爱个购商家入驻操作模板',
            looknum: '',
            downnum: '',
            type: 'word',
            cubage: '8797KB',
            time: ''
        }, {
            id: 4,
            url: 'http://source.aigegou.com/img/dls4.pptx',
            img: 'img/data/type2.jpg',
            titles: '员工跑商户谈单文件夹资料',
            looknum: '',
            downnum: '',
            type: 'ppt',
            cubage: '8552KB',
            time: ''
        }, {
            id: 5,
            url: 'http://source.aigegou.com/img/dls5.doc',
            img: 'img/data/type1.jpg',
            titles: '代理商市场答课问',
            looknum: '',
            downnum: '',
            type: 'word',
            cubage: '239KB',
            time: ''
        }, {
            id: 6,
            url: 'http://source.aigegou.com/img/dls6.doc',
            img: 'img/data/type1.jpg',
            titles: '代理商业务员跑业务流程',
            looknum: '',
            downnum: '',
            type: 'word',
            cubage: '221KB',
            time: ''
        }, {
            id: 7,
            url: 'http://source.aigegou.com/img/dls7.doc',
            img: 'img/data/type1.jpg',
            titles: '商户开发流程',
            looknum: '',
            downnum: '',
            type: 'word',
            cubage: '207KB',
            time: ''
        }, {
            id: 8,
            url: 'http://source.aigegou.com/img/dls8.ppt',
            img: 'img/data/type2.jpg',
            titles: '大客户如何开发',
            looknum: '',
            downnum: '',
            type: 'ppt',
            cubage: '1275KB',
            time: ''
        }, {
            id: 9,
            url: 'http://source.aigegou.com/img/dls9.pptx',
            img: 'img/data/type2.jpg',
            titles: '商户面谈思路及话术示例S2',
            looknum: '',
            downnum: '',
            type: 'ppt',
            cubage: '3694KB',
            time: ''
        }, {
            id: 10,
            url: 'http://source.aigegou.com/img/dls10.doc',
            img: 'img/data/type1.jpg',
            titles: '代理商薪酬制度',
            looknum: '',
            downnum: '',
            type: 'word',
            cubage: '244KB',
            time: ''
        }, {
            id: 11,
            url: 'http://source.aigegou.com/img/dls11.xlsx',
            img: 'img/data/type3.jpg',
            titles: '签约客户跟进表',
            looknum: '',
            downnum: '',
            type: 'Excel',
            cubage: '12KB',
            time: ''
        }, {
            id: 12,
            url: 'http://source.aigegou.com/img/dls12.xlsx',
            img: 'img/data/type3.jpg',
            titles: '区代客户关系管理统计表',
            looknum: '',
            downnum: '',
            type: 'Excel',
            cubage: '18KB',
            time: ''
        }, {
            id: 13,
            url: 'http://source.aigegou.com/img/dls13.xlsx',
            img: 'img/data/type3.jpg',
            titles: '商户合作费率',
            looknum: '',
            downnum: '',
            type: 'Excel',
            cubage: '22KB',
            time: ''
        }]
    }, {
        list: [{
            id: 1,
            url: 'http://source.aigegou.com/img/pxkj1.pdf',
            img: 'img/data/type4.jpg',
            titles: '爱个购智能安防',
            looknum: '',
            downnum: '',
            type: 'pdf',
            cubage: '1751KB',
            time: ''
        }, {
            id: 2,
            url: 'http://source.aigegou.com/img/pxkj2.ppt',
            img: 'img/data/type2.jpg',
            titles: '沟通技巧',
            looknum: '',
            downnum: '',
            type: 'ppt',
            cubage: '2568KB',
            time: ''
        }, {
            id: 3,
            url: 'http://source.aigegou.com/img/pxkj3.pdf',
            img: 'img/data/type4.jpg',
            titles: '行业培训',
            looknum: '',
            downnum: '',
            type: 'pdf',
            cubage: '5257KB',
            time: ''
        }, {
            id: 4,
            url: 'http://source.aigegou.com/img/pxkj4.pdf',
            img: 'img/data/type4.jpg',
            titles: '客情维护',
            looknum: '',
            downnum: '',
            type: 'pdf',
            cubage: '653KB',
            time: ''
        }, {
            id: 5,
            url: 'http://source.aigegou.com/img/pxkj5.ppt',
            img: 'img/data/type2.jpg',
            titles: '目标管理与时间管理',
            looknum: '',
            downnum: '',
            type: 'ppt',
            cubage: '2489KB',
            time: ''
        }, {
            id: 6,
            url: 'http://source.aigegou.com/img/pxkj6.pdf',
            img: 'img/data/type4.jpg',
            titles: '商户面谈思路及话术',
            looknum: '',
            downnum: '',
            type: 'pdf',
            cubage: '923KB',
            time: ''
        }, {
            id: 7,
            url: 'http://source.aigegou.com/img/pxkj7.pptx',
            img: 'img/data/type2.jpg',
            titles: '商务礼仪',
            looknum: '',
            downnum: '',
            type: 'ppt',
            cubage: '9490KB',
            time: ''
        }, {
            id: 8,
            url: 'http://source.aigegou.com/img/pxkj8.pdf',
            img: 'img/data/type4.jpg',
            titles: '十分钟路演',
            looknum: '',
            downnum: '',
            type: 'pdf',
            cubage: '6048KB',
            time: ''
        }, {
            id: 9,
            url: 'http://source.aigegou.com/img/pxkj9.pdf',
            img: 'img/data/type4.jpg',
            titles: '塑造团队',
            looknum: '',
            downnum: '',
            type: 'pdf',
            cubage: '2402KB',
            time: ''
        }, {
            id: 10,
            url: 'http://source.aigegou.com/img/pxkj10.pptx',
            img: 'img/data/type2.jpg',
            titles: '拖延症',
            looknum: '',
            downnum: '',
            type: 'ppt',
            cubage: '2339KB',
            time: ''
        }, {
            id: 11,
            url: 'http://source.aigegou.com/img/pxkj11.pdf',
            img: 'img/data/type4.jpg',
            titles: '运营推广演讲PPT',
            looknum: '',
            downnum: '',
            type: 'pdf',
            cubage: '2307KB',
            time: ''
        }, {
            id: 12,
            url: 'http://source.aigegou.com/img/pxkj12.ppt',
            img: 'img/data/type2.jpg',
            titles: '在销售中如何运用赞美的技巧',
            looknum: '',
            downnum: '',
            type: 'ppt',
            cubage: '1067KB',
            time: ''
        }, {
            id: 13,
            url: 'http://source.aigegou.com/img/pxkj13.pptx',
            img: 'img/data/type2.jpg',
            titles: '执行力',
            looknum: '',
            downnum: '',
            type: 'ppt',
            cubage: '187KB',
            time: ''
        }, {
            id: 14,
            url: 'http://source.aigegou.com/img/pxkj14.ppt',
            img: 'img/data/type2.jpg',
            titles: '职业经理人晋职',
            looknum: '',
            downnum: '',
            type: 'ppt',
            cubage: '486KB',
            time: ''
        }, {
            id: 15,
            url: 'http://source.aigegou.com/img/pxkj15.pptx',
            img: 'img/data/type2.jpg',
            titles: '职业素养塑造',
            looknum: '',
            downnum: '',
            type: 'ppt',
            cubage: '2142KB',
            time: ''
        }, {
            id: 16,
            url: 'http://source.aigegou.com/img/pxkj16.ppt',
            img: 'img/data/type2.jpg',
            titles: '做不被竞争淘汰的人',
            looknum: '',
            downnum: '',
            type: 'ppt',
            cubage: '1987KB',
            time: ''
        }]
    }, {
        list: [{
            id: 1,
            url: 'http://source.aigegou.com/img/ptjs1.ppt',
            img: 'img/data/type2.jpg',
            titles: '爱个购项目了解',
            looknum: '',
            downnum: '',
            type: 'ppt',
            cubage: '6490KB',
            time: ''
        }, {
            id: 2,
            url: 'http://source.aigegou.com/img/ptjs2.doc',
            img: 'img/data/type1.jpg',
            titles: '爱个购商户使用协议(2015年1月版)',
            looknum: '',
            downnum: '',
            type: 'word',
            cubage: '38KB',
            time: ''
        }, {
            id: 3,
            url: 'http://source.aigegou.com/img/ptjs3.ppt',
            img: 'img/data/type2.jpg',
            titles: '爱个购代理商系统操作手册',
            looknum: '',
            downnum: '',
            type: 'ppt',
            cubage: '3721KB',
            time: ''
        }, {
            id: 4,
            url: 'http://source.aigegou.com/img/ptjs4.ppt',
            img: 'img/data/type2.jpg',
            titles: '爱个购商户系统操作手册',
            looknum: '',
            downnum: '',
            type: 'ppt',
            cubage: '2096KB',
            time: ''
        }]
    }, {
        list: [{
            id: 1,
            url: 'http://source.aigegou.com/img/qyhb.zip',
            img: 'img/data/company1.jpg',
            titles: '海报',
            looknum: '',
            downnum: '',
            type: 'zip',
            cubage: '79.1MB',
            time: ''
        }, {
            id: 2,
            url: 'http://source.aigegou.com/img/qymp.zip',
            img: 'img/data/company2.jpg',
            titles: '名片',
            looknum: '',
            downnum: '',
            type: 'zip',
            cubage: '12.3MB',
            time: ''
        }, {
            id: 3,
            url: 'http://source.aigegou.com/img/qywh.zip',
            img: 'img/data/company3.jpg',
            titles: '文化墙',
            looknum: '',
            downnum: '',
            type: 'zip',
            cubage: '685MB',
            time: ''
        }, {
            id: 4,
            url: 'http://source.aigegou.com/img/qyxcd.zip',
            img: 'img/data/company4.jpg',
            titles: '宣传单页',
            looknum: '',
            downnum: '',
            type: 'zip',
            cubage: '19.5MB',
            time: ''
        }, {
            id: 5,
            url: 'http://source.aigegou.com/img/qyylb.zip',
            img: 'img/data/company5.jpg',
            titles: '易拉宝',
            looknum: '',
            downnum: '',
            type: 'zip',
            cubage: '58.7MB',
            time: ''
        }, {
            id: 6,
            url: 'http://source.aigegou.com/img/qyzj.zip',
            img: 'img/data/company6.jpg',
            titles: '展架',
            looknum: '',
            downnum: '',
            type: 'zip',
            cubage: '25.4MB',
            time: ''
        }]
    }

];