var m_list = [{
        list: [{
            id: 1,
            url: 'http://source.aigegou.com/img/dls1.doc',
            img: 'img/data/type1.jpg',
            titles: '公司注册流程',
            looknum: '5215',
            downnum: '324',
            type: 'word',
            cubage: '222KB',
            time: ''
        }, {
            id: 2,
            url: 'http://source.aigegou.com/img/dls2.doc',
            img: 'img/data/type1.jpg',
            titles: '办公地点和选址参考建议',
            looknum: '5314',
            downnum: '234',
            type: 'word',
            cubage: '207KB',
            time: ''
        }, {
            id: 3,
            url: 'http://source.aigegou.com/img/dls3.doc',
            img: 'img/data/type1.jpg',
            titles: '爱个购商家入驻操作模板',
            looknum: '4987',
            downnum: '324',
            type: 'word',
            cubage: '8797KB',
            time: ''
        }, {
            id: 4,
            url: 'http://source.aigegou.com/img/dls4.pptx',
            img: 'img/data/type2.jpg',
            titles: '员工跑商户谈单文件夹资料',
            looknum: '2364',
            downnum: '895',
            type: 'ppt',
            cubage: '8552KB',
            time: ''
        }, {
            id: 5,
            url: 'http://source.aigegou.com/img/dls5.doc',
            img: 'img/data/type1.jpg',
            titles: '代理商市场答课问',
            looknum: '3254',
            downnum: '236',
            type: 'word',
            cubage: '239KB',
            time: ''
        }, {
            id: 6,
            url: 'http://source.aigegou.com/img/dls6.doc',
            img: 'img/data/type1.jpg',
            titles: '代理商业务员跑业务流程',
            looknum: '7878',
            downnum: '362',
            type: 'word',
            cubage: '221KB',
            time: ''
        }, {
            id: 7,
            url: 'http://source.aigegou.com/img/dls7.doc',
            img: 'img/data/type1.jpg',
            titles: '商户开发流程',
            looknum: '7451',
            downnum: '123',
            type: 'word',
            cubage: '207KB',
            time: ''
        }, {
            id: 8,
            url: 'http://source.aigegou.com/img/dls8.ppt',
            img: 'img/data/type2.jpg',
            titles: '大客户如何开发',
            looknum: '9415',
            downnum: '175',
            type: 'ppt',
            cubage: '1275KB',
            time: ''
        }, {
            id: 9,
            url: 'http://source.aigegou.com/img/dls9.pptx',
            img: 'img/data/type2.jpg',
            titles: '商户面谈思路及话术示例S2',
            looknum: '1557',
            downnum: '352',
            type: 'ppt',
            cubage: '3694KB',
            time: ''
        }, {
            id: 10,
            url: 'http://source.aigegou.com/img/dls10.doc',
            img: 'img/data/type1.jpg',
            titles: '代理商薪酬制度',
            looknum: '8215',
            downnum: '261',
            type: 'word',
            cubage: '244KB',
            time: ''
        }, {
            id: 11,
            url: 'http://source.aigegou.com/img/dls11.xlsx',
            img: 'img/data/type3.jpg',
            titles: '签约客户跟进表',
            looknum: '7145',
            downnum: '362',
            type: 'Excel',
            cubage: '12KB',
            time: ''
        }, {
            id: 12,
            url: 'http://source.aigegou.com/img/dls12.xlsx',
            img: 'img/data/type3.jpg',
            titles: '区代客户关系管理统计表',
            looknum: '3621',
            downnum: '895',
            type: 'Excel',
            cubage: '18KB',
            time: ''
        }, {
            id: 13,
            url: 'http://source.aigegou.com/img/dls13.xlsx',
            img: 'img/data/type3.jpg',
            titles: '商户合作费率',
            looknum: '4516',
            downnum: '884',
            type: 'Excel',
            cubage: '22KB',
            time: ''
        }]
    }, {
        list: [{
            id: 1,
            url: 'http://source.aigegou.com/0820dzsw.pptx',
            img: 'img/data/type2.jpg',
            titles: '电子商务',
            looknum: '88',
            downnum: '42',
            type: 'ppt',
            cubage: '4.7MB',
            time: ''
        }, {
            id: 2,
            url: 'http://source.aigegou.com/0820ddg.pptx',
            img: 'img/data/type2.jpg',
            titles: '叮大哥项目简介（赵丽娟）',
            looknum: '102',
            downnum: '56',
            type: 'ppt',
            cubage: '3MB',
            time: ''
        }, {
            id: 3,
            url: 'http://source.aigegou.com/0820hdch.pptx',
            img: 'img/data/type2.jpg',
            titles: '活动策划--凡雪林',
            looknum: '64',
            downnum: '24',
            type: 'ppt',
            cubage: '1.26MB',
            time: ''
        }, {
            id: 4,
            url: 'http://source.aigegou.com/0820store.ppt',
            img: 'img/data/type2.jpg',
            titles: '开发商户思路',
            looknum: '62',
            downnum: '32',
            type: 'ppt',
            cubage: '689KB',
            time: ''
        }, {
            id: 5,
            url: 'http://source.aigegou.com/0820tgs.ppt',
            img: 'img/data/type2.jpg',
            titles: '社区推广商',
            looknum: '89',
            downnum: '24',
            type: 'ppt',
            cubage: '651KB',
            time: ''
        }, {
            id: 6,
            url: 'http://source.aigegou.com/img/pxkj1.pdf',
            img: 'img/data/type4.jpg',
            titles: '爱个购智能安防',
            looknum: '5116',
            downnum: '264',
            type: 'pdf',
            cubage: '1751KB',
            time: ''
        }, {
            id: 7,
            url: 'http://source.aigegou.com/img/pxkj2.ppt',
            img: 'img/data/type2.jpg',
            titles: '沟通技巧',
            looknum: '9845',
            downnum: '516',
            type: 'ppt',
            cubage: '2568KB',
            time: ''
        }, {
            id: 8,
            url: 'http://source.aigegou.com/img/pxkj3.pdf',
            img: 'img/data/type4.jpg',
            titles: '行业培训',
            looknum: '8465',
            downnum: '123',
            type: 'pdf',
            cubage: '5257KB',
            time: ''
        }, {
            id: 9,
            url: 'http://source.aigegou.com/img/pxkj4.pdf',
            img: 'img/data/type4.jpg',
            titles: '客情维护',
            looknum: '8955',
            downnum: '215',
            type: 'pdf',
            cubage: '653KB',
            time: ''
        }, {
            id: 10,
            url: 'http://source.aigegou.com/img/pxkj5.ppt',
            img: 'img/data/type2.jpg',
            titles: '目标管理与时间管理',
            looknum: '8145',
            downnum: '232',
            type: 'ppt',
            cubage: '2489KB',
            time: ''
        }, {
            id: 11,
            url: 'http://source.aigegou.com/img/pxkj6.pdf',
            img: 'img/data/type4.jpg',
            titles: '商户面谈思路及话术',
            looknum: '9454',
            downnum: '235',
            type: 'pdf',
            cubage: '923KB',
            time: ''
        }, {
            id: 12,
            url: 'http://source.aigegou.com/img/pxkj7.pptx',
            img: 'img/data/type2.jpg',
            titles: '商务礼仪',
            looknum: '1324',
            downnum: '944',
            type: 'ppt',
            cubage: '9490KB',
            time: ''
        }, {
            id: 13,
            url: 'http://source.aigegou.com/img/pxkj8.pdf',
            img: 'img/data/type4.jpg',
            titles: '十分钟路演',
            looknum: '5156',
            downnum: '941',
            type: 'pdf',
            cubage: '6048KB',
            time: ''
        }, {
            id: 14,
            url: 'http://source.aigegou.com/img/pxkj9.pdf',
            img: 'img/data/type4.jpg',
            titles: '塑造团队',
            looknum: '3264',
            downnum: '564',
            type: 'pdf',
            cubage: '2402KB',
            time: ''
        }, {
            id: 15,
            url: 'http://source.aigegou.com/img/pxkj10.pptx',
            img: 'img/data/type2.jpg',
            titles: '拖延症',
            looknum: '4874',
            downnum: '232',
            type: 'ppt',
            cubage: '2339KB',
            time: ''
        }, {
            id: 16,
            url: 'http://source.aigegou.com/img/pxkj11.pdf',
            img: 'img/data/type4.jpg',
            titles: '运营推广演讲PPT',
            looknum: '6854',
            downnum: '216',
            type: 'pdf',
            cubage: '2307KB',
            time: ''
        }, {
            id: 17,
            url: 'http://source.aigegou.com/img/pxkj12.ppt',
            img: 'img/data/type2.jpg',
            titles: '在销售中如何运用赞美的技巧',
            looknum: '5465',
            downnum: '325',
            type: 'ppt',
            cubage: '1067KB',
            time: ''
        }, {
            id: 18,
            url: 'http://source.aigegou.com/img/pxkj13.pptx',
            img: 'img/data/type2.jpg',
            titles: '执行力',
            looknum: '6541',
            downnum: '524',
            type: 'ppt',
            cubage: '187KB',
            time: ''
        }, {
            id: 19,
            url: 'http://source.aigegou.com/img/pxkj14.ppt',
            img: 'img/data/type2.jpg',
            titles: '职业经理人晋职',
            looknum: '5416',
            downnum: '965',
            type: 'ppt',
            cubage: '486KB',
            time: ''
        }, {
            id: 20,
            url: 'http://source.aigegou.com/img/pxkj15.pptx',
            img: 'img/data/type2.jpg',
            titles: '职业素养塑造',
            looknum: '9415',
            downnum: '541',
            type: 'ppt',
            cubage: '2142KB',
            time: ''
        }, {
            id: 21,
            url: 'http://source.aigegou.com/img/pxkj16.ppt',
            img: 'img/data/type2.jpg',
            titles: '做不被竞争淘汰的人',
            looknum: '5894',
            downnum: '541',
            type: 'ppt',
            cubage: '1987KB',
            time: ''
        }]
    }, {
        list: [{
            id: 1,
            url: 'http://source.aigegou.com/img/ptjs1.ppt',
            img: 'img/data/type2.jpg',
            titles: '爱个购项目了解',
            looknum: '5416',
            downnum: '854',
            type: 'ppt',
            cubage: '6490KB',
            time: ''
        }, {
            id: 2,
            url: 'http://source.aigegou.com/img/ptjs2.doc',
            img: 'img/data/type1.jpg',
            titles: '爱个购商户使用协议(2015年1月版)',
            looknum: '8415',
            downnum: '325',
            type: 'word',
            cubage: '38KB',
            time: ''
        }, {
            id: 3,
            url: 'http://source.aigegou.com/img/ptjs3.ppt',
            img: 'img/data/type2.jpg',
            titles: '爱个购代理商系统操作手册',
            looknum: '6513',
            downnum: '584',
            type: 'ppt',
            cubage: '3721KB',
            time: ''
        }, {
            id: 4,
            url: 'http://source.aigegou.com/img/ptjs4.ppt',
            img: 'img/data/type2.jpg',
            titles: '爱个购商户系统操作手册',
            looknum: '5412',
            downnum: '541',
            type: 'ppt',
            cubage: '2096KB',
            time: ''
        }]
    }, {
        list: [{
            id: 1,
            url: 'http://source.aigegou.com/img/qyhb.zip',
            img: 'img/data/company1.jpg',
            titles: '海报',
            looknum: '5465',
            downnum: '256',
            type: 'zip',
            cubage: '79.1MB',
            time: ''
        }, {
            id: 2,
            url: 'http://source.aigegou.com/img/qymp.zip',
            img: 'img/data/company2.jpg',
            titles: '名片',
            looknum: '8994',
            downnum: '751',
            type: 'zip',
            cubage: '12.3MB',
            time: ''
        }, {
            id: 3,
            url: 'http://source.aigegou.com/img/qywh.zip',
            img: 'img/data/company3.jpg',
            titles: '文化墙',
            looknum: '6157',
            downnum: '851',
            type: 'zip',
            cubage: '685MB',
            time: ''
        }, {
            id: 4,
            url: 'http://source.aigegou.com/img/qyxcd.zip',
            img: 'img/data/company4.jpg',
            titles: '宣传单页',
            looknum: '1255',
            downnum: '235',
            type: 'zip',
            cubage: '19.5MB',
            time: ''
        }, {
            id: 5,
            url: 'http://source.aigegou.com/img/qyylb.zip',
            img: 'img/data/company5.jpg',
            titles: '易拉宝',
            looknum: '5415',
            downnum: '511',
            type: 'zip',
            cubage: '58.7MB',
            time: ''
        }, {
            id: 6,
            url: 'http://source.aigegou.com/img/qyzj.zip',
            img: 'img/data/company6.jpg',
            titles: '展架',
            looknum: '5455',
            downnum: '454',
            type: 'zip',
            cubage: '25.4MB',
            time: ''
        }]
    }

];